"""init schema

Revision ID: 34eb176e2f7b
Revises: 
Create Date: 2026-06-02 12:58:14.747680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34eb176e2f7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fornecedores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('categorias', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('solicitante', 'controle', 'fornecedor', name='user_role'), nullable=False),
    sa.Column('team', sa.String(length=200), nullable=True),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_fornecedor_id'), 'usuarios', ['fornecedor_id'], unique=False)
    op.create_table('solicitacoes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('numero', sa.String(length=30), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('area', sa.String(length=200), nullable=True),
    sa.Column('prioridade', sa.String(length=30), nullable=True),
    sa.Column('categoria', sa.String(length=100), nullable=True),
    sa.Column('solicitante_id', sa.UUID(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('sistemas_impactados', sa.Text(), nullable=True),
    sa.Column('entregaveis', sa.Text(), nullable=True),
    sa.Column('complexidade', sa.String(length=30), nullable=True),
    sa.Column('ambiente', sa.String(length=50), nullable=True),
    sa.Column('prazo_entrega', sa.String(length=30), nullable=True),
    sa.Column('prazo_resposta', sa.String(length=30), nullable=True),
    sa.Column('modalidade', sa.String(length=100), nullable=True),
    sa.Column('tipo_servico', sa.String(length=100), nullable=True),
    sa.Column('subtipo', sa.String(length=200), nullable=True),
    sa.Column('senioridade', sa.String(length=30), nullable=True),
    sa.Column('fin_type', sa.String(length=10), nullable=True),
    sa.Column('iniciativa', sa.String(length=50), nullable=True),
    sa.Column('urgencia', sa.String(length=30), nullable=True),
    sa.Column('metodologia_pf', sa.String(length=20), nullable=True),
    sa.Column('form_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('aguardando_controle', 'rejeitada_controle', 'aguardando_proposta', 'proposta_enviada', 'aceita', 'recusada', name='solicitacao_status'), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=True),
    sa.Column('parecer_controle', sa.Text(), nullable=True),
    sa.Column('estimativa_aprovada', sa.String(length=100), nullable=True),
    sa.Column('decisao_solicitante', sa.String(length=20), nullable=True),
    sa.Column('aval_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decidido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['solicitante_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacoes_fornecedor_id'), 'solicitacoes', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_solicitacoes_numero'), 'solicitacoes', ['numero'], unique=True)
    op.create_index(op.f('ix_solicitacoes_solicitante_id'), 'solicitacoes', ['solicitante_id'], unique=False)
    op.create_table('analises_pf',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solicitacao_id', sa.UUID(), nullable=False),
    sa.Column('metodologia', sa.String(length=20), nullable=False),
    sa.Column('aba', sa.String(length=50), nullable=True),
    sa.Column('total_campos', sa.Integer(), nullable=False),
    sa.Column('total_preenchidos', sa.Integer(), nullable=False),
    sa.Column('total_pendentes', sa.Integer(), nullable=False),
    sa.Column('completo', sa.Boolean(), nullable=False),
    sa.Column('campos', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('pendentes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resumo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analises_pf_solicitacao_id'), 'analises_pf', ['solicitacao_id'], unique=False)
    op.create_table('propostas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solicitacao_id', sa.UUID(), nullable=False),
    sa.Column('fornecedor_id', sa.UUID(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('prazo', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('arquivo_nome', sa.String(length=300), nullable=True),
    sa.Column('status', sa.Enum('enviada', 'aceita', 'recusada', name='proposta_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_propostas_fornecedor_id'), 'propostas', ['fornecedor_id'], unique=False)
    op.create_index(op.f('ix_propostas_solicitacao_id'), 'propostas', ['solicitacao_id'], unique=False)
    op.create_table('solicitacao_documentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('solicitacao_id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=300), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=True),
    sa.Column('tamanho', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['solicitacao_id'], ['solicitacoes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solicitacao_documentos_solicitacao_id'), 'solicitacao_documentos', ['solicitacao_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_solicitacao_documentos_solicitacao_id'), table_name='solicitacao_documentos')
    op.drop_table('solicitacao_documentos')
    op.drop_index(op.f('ix_propostas_solicitacao_id'), table_name='propostas')
    op.drop_index(op.f('ix_propostas_fornecedor_id'), table_name='propostas')
    op.drop_table('propostas')
    op.drop_index(op.f('ix_analises_pf_solicitacao_id'), table_name='analises_pf')
    op.drop_table('analises_pf')
    op.drop_index(op.f('ix_solicitacoes_solicitante_id'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_numero'), table_name='solicitacoes')
    op.drop_index(op.f('ix_solicitacoes_fornecedor_id'), table_name='solicitacoes')
    op.drop_table('solicitacoes')
    op.drop_index(op.f('ix_usuarios_fornecedor_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('fornecedores')
    # ### end Alembic commands ###
